# Generated by Django 3.2.9 on 2021-11-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=200, verbose_name='Prenom')),
                ('last_name', models.CharField(max_length=200, verbose_name='Nom')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Pseudo')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=50, verbose_name='telephone')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_joined', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
