# Generated by Django 3.2.4 on 2021-12-23 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, verbose_name='Numero de la commande')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prenom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('phone', models.CharField(max_length=15, verbose_name='Telephone')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('address_line_1', models.CharField(max_length=50, verbose_name='Adresse 1')),
                ('address_line_2', models.CharField(blank=True, max_length=50, verbose_name='Adresse 2')),
                ('country', models.CharField(max_length=50, verbose_name='Pays')),
                ('state', models.CharField(max_length=50, verbose_name='Etat')),
                ('city', models.CharField(max_length=50, verbose_name='Ville')),
                ('order_note', models.CharField(blank=True, max_length=200, verbose_name='Note de la commande')),
                ('order_total', models.FloatField(verbose_name='Commande totale')),
                ('tax', models.FloatField(verbose_name='Taxe')),
                ('status', models.CharField(choices=[('Nouvelle', 'Nouvelle'), ('Acceptée', 'Acceptée'), ('Terminée', 'Terminée'), ('Annulée', 'Annulée')], default='Nouveau', max_length=20)),
                ('ip', models.CharField(blank=True, max_length=10)),
                ('is_ordered', models.BooleanField(default=False, verbose_name='Commande deja effectuée ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Crée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, verbose_name='ID paiement')),
                ('payment_method', models.CharField(max_length=100, verbose_name='Moyen de paiement')),
                ('amount_paid', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Paiement effectué')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiement',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Couleur')),
                ('size', models.CharField(max_length=50, verbose_name='Taille')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('product_price', models.FloatField(verbose_name="Prix du l'article")),
                ('ordered', models.BooleanField(default=False, verbose_name='Deja commandé ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Commande')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment', verbose_name='Paiement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variation', verbose_name="Caracteristiques de l'article")),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment', verbose_name='Paiement'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
