# Generated by Django 3.2.4 on 2021-12-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=70, unique=True, verbose_name='Nom de la categorie')),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('overview', models.TextField(verbose_name='Aperçu')),
                ('description', models.TextField(max_length=300)),
                ('is_available', models.BooleanField(default=False, verbose_name='Disponible ?')),
                ('categories_image', models.ImageField(blank=True, upload_to='photos/categorie', verbose_name='image')),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
