# Generated by Django 3.2.4 on 2021-12-23 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='banner/images')),
                ('image2', models.ImageField(upload_to='banner/images')),
            ],
            options={
                'verbose_name': 'Bannière',
                'verbose_name_plural': 'Bannières',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Article')),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(blank=True, choices=[('GN', 'GUINEE'), ('US', 'USA'), ('FR', 'FRANCE'), ('MA', 'MAROC'), ('CA', 'CANADA'), ('BR', 'BRESIL'), ('AR', 'ARGENTINE'), ('DE', 'ALLEMAGNE'), ('IT', 'ITALIE'), ('ES', 'ESPAGNE'), ('PT', 'PORTUGAL'), ('RU', 'RUSSIE'), ('IN', 'INDE'), ('ID', 'INDONESIE'), ('IN', 'Indiana'), ('MY', 'MALAYSIE'), ('CN', 'CHINE'), ('JP', 'JAPON'), ('UK', 'ANGLETERRE'), ('NL', 'PAYS BAS'), ('BE', 'BELGIQUE')], max_length=50, verbose_name='Fabricant')),
                ('condition', models.CharField(blank=True, choices=[('Nouveau', 'Nouveau'), ('Solde', 'Solde')], max_length=200)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default='2021', verbose_name='Année')),
                ('price', models.IntegerField(default=0, verbose_name='Prix')),
                ('features', models.CharField(blank=True, choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=200, verbose_name='Caracteristiques')),
                ('specification', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('image1', models.ImageField(blank=True, upload_to='')),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('image3', models.ImageField(blank=True, upload_to='')),
                ('image4', models.ImageField(blank=True, upload_to='')),
                ('stock', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible ?')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='Livraison gratuite ?')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='categorie.category', verbose_name="Categorie de l'article")),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('couleur', 'couleur'), ('taille', 'taille')], max_length=100, verbose_name='Caracteristiques')),
                ('variation_value', models.CharField(max_length=100, verbose_name='valeur de la caracteristique')),
                ('is_active', models.BooleanField(default=True, verbose_name='Deja active ?')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Date de creation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Article')),
            ],
        ),
    ]
