# Generated by Django 3.2.9 on 2021-11-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Article au panier', 'verbose_name_plural': 'Articles au panier'},
        ),
    ]
