# Generated by Django 3.2.9 on 2021-11-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20211119_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(verbose_name='quantité'),
        ),
    ]
